version: '3.8'
services:
  prom:
    image: prom/prometheus
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    network_mode: "host"
    ports:
     - 9090:9090
  grafana:
    image: grafana/grafana
    network_mode: "host"
    ports:
     - 3000:3000
    depends_on:
      - prom
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
  dnsmon-go:
    build: ./
    network_mode: "host"
    command: "-interface eth0"
    ports:
     - 8080:8080
    restart: on-failure
