{
 "title": "dnsmon-go",
 "description": "A sample dashboard to get you started",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (opcode, rcode, type) (rate(dns_record_counter[5m]))",
     "legendFormat": "{{type}} {{rcode}}"
    }
   ]
  },
  {
   "title": "DNS Speedometer",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dns_record_counter[1m]))"
    }
   ]
  },
  {
   "title": "Sum of Queries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(dns_record_counter)" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(dns_record_counter[1m]))"
    }
   ]
  },
  {
   "title": "Table of Things",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(dns_record_counter[5m])" }
   ]
  }
 ]
}