name: dnsmon-go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
      id: go
    - name: Install dependencies
      run: sudo apt-get -qqy install libpcap-dev

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Download go modules
      run: go mod download

    - name: Verify go modules
      run: go mod verify

    - name: Build
      run: go build -v .
